<a href="https://colab.research.google.com/github/AliRizvi14/CE888/blob/master/lab6/recommended_system.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [3]:

df=pd.read_csv('https://raw.githubusercontent.com/albanda/CE888/master/lab4-recommender/jester-data-1.csv')
df

,74,-7.82,8.79,-9.66,-8.16,-7.52,-8.5,-9.85,4.17,-8.98,...,2.82.2,99.18,99.19,99.20,99.21,99.22,-5.63,99.23,99.24,99.25
0,100,4.08,-0.29,6.36,4.37,-2.38,-9.66,-0.73,-5.34,8.88,...,2.82,-4.95,-0.29,7.86,-0.19,-2.14,3.06,0.34,-4.32,1.07
1,49,99.00,99.00,99.00,99.00,9.03,9.27,9.03,9.27,99.00,...,99.00,99.00,99.00,9.08,99.00,99.00,99.00,99.00,99.00,99.00
2,48,99.00,8.35,99.00,99.00,1.80,8.16,-2.82,6.21,99.00,...,99.00,99.00,99.00,0.53,99.00,99.00,99.00,99.00,99.00,99.00
3,91,8.50,4.61,-4.17,-5.39,1.36,1.60,7.04,4.61,-0.44,...,5.19,5.58,4.27,5.19,5.73,1.55,3.11,6.55,1.80,1.60
4,100,-6.17,-3.54,0.44,-8.50,-7.09,-4.32,-8.69,-0.87,-6.65,...,-3.54,-6.89,-0.68,-2.96,-2.18,-3.35,0.05,-9.08,-5.05,-3.45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24977,100,0.44,7.43,9.08,2.33,3.20,6.75,-8.79,-0.53,-8.74,...,8.83,-1.21,9.22,-6.70,8.45,9.03,6.55,8.69,8.79,7.43
24978,91,9.13,-8.16,8.59,9.08,0.87,-8.93,-3.50,5.78,-8.11,...,-1.17,-5.73,-1.46,0.24,9.22,-8.20,-7.23,-8.59,9.13,8.45
24979,39,99.00,99.00,99.00,99.00,-7.77,99.00,6.70,-6.75,99.00,...,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00
24980,37,99.00,99.00,99.00,99.00,-9.71,99.00,4.56,-8.30,99.00,...,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00
24981,72,2.43,2.67,-3.98,4.27,-2.28,7.33,2.33,4.56,6.75,...,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00,99.00

In [4]:
df.columns

Index(['74', '-7.82', '8.79', '-9.66', '-8.16', '-7.52', '-8.5', '-9.85',
       '4.17', '-8.98',
       ...
       '2.82.2', '99.18', '99.19', '99.20', '99.21', '99.22', '-5.63', '99.23',
       '99.24', '99.25'],
      dtype='object', length=101)

In [13]:
df.isna().sum().tail(50)

-8.69      0
-7.14.1    0
3.2        0
8.3        0
-4.56      0
0.92       0
-9.13.1    0
-9.42      0
2.82       0
-8.64      0
8.59       0
3.59       0
-6.84      0
-9.03.1    0
2.82.1     0
-1.36      0
-9.08.2    0
8.3.1      0
5.68       0
-4.81      0
99         0
99.1       0
99.2       0
99.3       0
99.4       0
99.5       0
99.6       0
-9.42.1    0
99.7       0
99.8       0
99.9       0
-7.72      0
99.10      0
99.11      0
99.12      0
99.13      0
99.14      0
99.15      0
99.16      0
99.17      0
2.82.2     0
99.18      0
99.19      0
99.20      0
99.21      0
99.22      0
-5.63      0
99.23      0
99.24      0
99.25      0
dtype: int64